fixed #89
mobility0/comado-plugin pull request #103
Opened 2021-05-23 03:16 UTC by nboufSD

2021-05-23 04:28 UTC, dadaa requested changes

2021-05-23 04:28 UTC, dadaa commented on index.html
> +          x: INIT_IMAGE_XCOOD + Number((result[i]["time"] - newMinTimestamp) / 1000) * TIME_MAGNIFICATION ,
1000 で割る理由ってなんでしたっけ？

2021-05-23 04:28 UTC, dadaa commented on index.html
> +      for (let i = 0; i < allOfIds.length; i++) {
newMinTimestamp と newMaxTimestamp は、このループで計算したらどうでしょうか？

2021-05-23 07:12 UTC, nboufSD commented on index.html
> +          x: INIT_IMAGE_XCOOD + Number((result[i]["time"] - newMinTimestamp) / 1000) * TIME_MAGNIFICATION ,
初期時間（newMinTimestamp）と貼るimageの時間(result[i]["time"])との差をx座標としたいのですが、そのまま差をとってx座標にすると1秒でxが1000進んでしまう（unixtimeがミリ秒なので）ので、1000で割って秒にして使うという感じです。
また、そのまま秒で使うと1秒で1しか進まない（ボード上でほぼ動かない）ので、TIME_MAGNIFICATIONをかけて、1秒でTIME_MAGNIFICATIONずつ進む様にしています

2021-05-23 07:14 UTC, nboufSD commented on index.html
> +      for (let i = 0; i < allOfIds.length; i++) {
ループで計算すると、計算量が増えてしまうのではないかと思ったのですが、大丈夫なのでしょうか…？

2021-05-23 08:18 UTC, dadaa commented on index.html
> +      for (let i = 0; i < allOfIds.length; i++) {
なんで計算量増えるんです？

2021-05-23 08:21 UTC, dadaa commented on index.html
> +          x: INIT_IMAGE_XCOOD + Number((result[i]["time"] - newMinTimestamp) / 1000) * TIME_MAGNIFICATION ,
TIME_MAGNIFICATION にその値も含ませたらどうですか？

2021-05-23 09:37 UTC, nboufSD commented on index.html
> +          x: INIT_IMAGE_XCOOD + Number((result[i]["time"] - newMinTimestamp) / 1000) * TIME_MAGNIFICATION ,
確かに倍率という意味だと、含ませるべきですね…
修正します！

2021-05-23 09:54 UTC, nboufSD commented on index.html
> +      for (let i = 0; i < allOfIds.length; i++) {
ループの中に書くと、ループの回数分計算する必要があるかと思った（今は一回計算するだけなので）のですが、僕が何か勘違いしてたりしますか…？

2021-05-23 10:38 UTC, dadaa commented on index.html
> +      for (let i = 0; i < allOfIds.length; i++) {
```
const newMaxTimestamp = Math.max.apply(null,result.map(x => x.time));
```
これを日本語にすると、 result の配列分ループしながら time を返し、result と同じ配列を新たに作ったあとに Math.max() で与えられた全ての数値を総当りして max を探して newMaxTimestamp に格納するということになります。
配列を作るのは重い処理ですし、ループするのと比べると何度か余計なことをしているように思います。

2021-05-23 11:57 UTC, nboufSD commented on index.html
> +      for (let i = 0; i < allOfIds.length; i++) {
ありがとうございます！
理解できました。
確かに、一文で書いているだけで実際はループを2回やって配列を作っているのと同様ですね…
この75行目のfor文では、allOfIds（重複なし）の回数しかループしていないのですが、mapやMath.maxの代わりになるにはどの様に書くべきでしょうか…？

また、今思いついたのですが、サーバーから取得したデータの順列が保持されることが確定なら、
const newMaxTimestamp = result[-1].time
の様に書いても良いのかなと思ったのですが、どうでしょうか？

2021-05-23 12:56 UTC, dadaa requested changes
ひとまずコメントどおりに修正お願いします。
ひとしきり今の issue が終わったら、ちょっとアルゴリズムを見直しましょう。
もう少し最適化できるんじゃないかと思ったりするので。

2021-05-23 12:56 UTC, dadaa commented on index.html
>        }
```
const newMinTimestamp = minTimestamp === Number.MAX_VALUE ? result[0].time : minTimestamp;
```

2021-05-23 12:56 UTC, dadaa commented on index.html
> +      let newMaxTimestamp = 0;
```
let newMaxTimestamp = minTimestamp;
```
にする必要はある？

2021-05-23 12:56 UTC, dadaa commented on index.html
> +        newMaxTimestamp = image.time > newMaxTimestamp ? image.time : newMaxTimestamp
```
newMaxTimestamp = Math.max(image.time, newMaxTimestamp);
```

2021-05-24 05:58 UTC, nboufSD commented on index.html
>        }
承知しました！
ありがとうございます

2021-05-24 06:08 UTC, nboufSD commented on index.html
> +        newMaxTimestamp = image.time > newMaxTimestamp ? image.time : newMaxTimestamp
ありがとうございます！

2021-05-24 06:19 UTC, nboufSD commented on index.html
> +      let newMaxTimestamp = 0;
ボードに何も貼られていない時の最小時刻：result[0].time
ボードにimageが貼られている時の最小時刻：minTimestamp
なので、ボードにimageが貼られている状態の時、newMinTimestamp = minTimestampとする必要があると考えています！

2021-05-24 10:32 UTC, dadaa approved these changes

2021-05-24 11:27 UTC, dadaa approved these changes

2021-05-24 11:27 UTC, merged