fixed_#90
mobility0/comado-plugin pull request #104
Opened 2021-05-23 03:27 UTC by nboufSD

2021-05-23 04:30 UTC, dadaa requested changes

2021-05-23 04:30 UTC, dadaa commented on index.html
> +        // 既にボードに貼られている時刻テキストの枚数分スキップすることで、更新分のみ貼る様にする
intervalTime / DIVIDED_TIME + 1 まで 0 から 1ずつプラスしていく数と existTimes.length  が、なぜ関連付けされるのかがわからないのです。

2021-05-23 07:41 UTC, nboufSD commented on index.html
> +        // 既にボードに貼られている時刻テキストの枚数分スキップすることで、更新分のみ貼る様にする
intervalTimeは一番新しいimageの時間と初期時間との差（経過時間）で、このintervalTimeをDIVIDED_TIME（今は60000[ms]）で割ることで、何分経過したかを計算します。（小数点以下切り捨て）
この分数を時間ラベルの数にするのですが、このままだと、切り捨てられた部分のラベルがないため、+1して補うという感じです。
また、intervalTime / DIVIDED_TIME + 1 は貼るべき時間ラベルの数なのですが、更新する時に、既に時間ラベルが貼られていた場合、再度同じラベルが貼られてしまう問題が発生します。
これを回避するために、existTimes.length（既に貼られている時刻ラベルの数）でスキップします。

例）
intervalTime = 182000[ms]
DIVIDED_TIME = 60000[ms]（=1[min]）
の場合
intervalTime / DIVIDED_TIME  = 3 [min]
つまり、3分経過しているので、1分、２分、3分の３つのラベルが必要ですが、端数の2000[ms]の地点が存在するため+1して、1分、２分、3分、4分の4つのラベルを貼ります。

また、existTimes.length = 2であった場合は、1分、２分の2つのラベルは既に貼られているため、for文では、2つのループをスキップします

2021-05-23 08:25 UTC, dadaa commented on index.html
> +        // 既にボードに貼られている時刻テキストの枚数分スキップすることで、更新分のみ貼る様にする
あー、existTimes は時間を示すラベルの話か。
existTimeLabels とリネームしてもらっても良いですか？
（どうもうまく名前とコンポーネントが結ばなくって、、ごめんなさい）
あと、その分のループをスキップするぐらいなら、初めからループしないようにすれば良いのでは？
```
for (let i = existTimes.length; i < intervalTime / DIVIDED_TIME + 1 ; i++) {
```
とか。

2021-05-23 09:58 UTC, nboufSD commented on index.html
> +        // 既にボードに貼られている時刻テキストの枚数分スキップすることで、更新分のみ貼る様にする
こちらこそ説明不足で申し訳なかったです！
javascriptのfor文で初期値を指定できないものだと思っていました…
修正します！

2021-05-24 10:31 UTC, dadaa approved these changes

2021-05-24 10:31 UTC, merged