fixed #91
mobility0/comado-plugin pull request #105
Opened 2021-05-23 03:35 UTC by nboufSD

2021-05-23 04:31 UTC, dadaa requested changes

2021-05-23 04:31 UTC, dadaa commented on index.html
> +          console.log(result[i].info.color);
console 散見されますが、ユーザの手がかりとして残す以外は基本的に削除してもらいたいです。

2021-05-23 07:42 UTC, nboufSD commented on index.html
> +          console.log(result[i].info.color);
すいません！
削除します！

2021-05-24 10:31 UTC, dadaa approved these changes

2021-05-24 10:32 UTC, merged