fixed #109
mobility0/comado-plugin pull request #111
Opened 2021-05-24 11:52 UTC by nboufSD

2021-05-24 17:59 UTC, nboufSD commented
参加者のpeerIdをボードのmetadataで管理する様に変更しました。
また、それに従って一度消されたuserNameは、再びpluginを作動させても貼られない様にしました。
（かなりコードが変わったので、細かくコメントを入れています。）

よろしくお願いします！

2021-05-24 22:11 UTC, dadaa requested changes

2021-05-24 22:11 UTC, dadaa commented on index.html
> +      }).sort((current, next) => current.order - next.order);
なんかもっとシンプルにできる気がします。ようは、ユーザ軸(縦軸)の場所がわかればいいんですよね？
```
for (const item of result) {
  const index = userAxisOrders.findIndex(user => user.id === item.id);
  if (index >= 0) {
    // すでにその ID の軸要素はあるので無視。
    continue;
  }
  userAxisOrders.push({ id: item.id, order: index + 1 });
}
```
こんなんで事足りるんじゃないですかね？

2021-05-25 03:00 UTC, nboufSD commented on index.html
> +      existUsers = existUsers?.users ? existUsers : {users: []};
確かにnameとかは入っていないので、適していませんね…
これから気をつけます１

2021-05-25 03:31 UTC, nboufSD commented on index.html
> +      }).sort((current, next) => current.order - next.order);
少し変更した部分もありますが、送ってくださったコードで正常に動作しました！
（こんなに短くなると思って無かったです…ありがとうございます！）

2021-05-25 04:19 UTC, dadaa requested changes

2021-05-25 04:19 UTC, dadaa commented on index.html
> +      const userAxisOrders = metadata?.userOrders || [];
metadata は null になる可能性がありますか？
もしなければ ? は削除してください。

2021-05-25 04:19 UTC, dadaa commented on index.html
> +        userAxisOrders.push({ id: item.peerId, order: userAxisOrders.length + 1 });
ここで、label もプッシュしてしまいましょう。
```
userAxisOrders.push({ id: item.peerId, order: userAxisOrders.length + 1, label:  item.audience.name});
```

2021-05-25 04:19 UTC, dadaa commented on index.html
> +        const index = result.findIndex(item => item.peerId === userAxisOrders[i].id);
この行要らなくなります。

2021-05-25 04:19 UTC, dadaa commented on index.html
>            text: result[index].audience.name,
```
text: userAxisOrders[i].label,
```

2021-05-25 04:24 UTC, dadaa requested changes

2021-05-25 04:24 UTC, dadaa commented on index.html
> +        userAxisOrders.push({ id: item.peerId, order: userAxisOrders.length + 1 });
あれ？もうここに以下のコードいれてラベルの widget 作ってもいいんじゃない？
```
miro.board.widgets.create({
  type: 'text',
  text: item.audience.name,
  ...
});
```

2021-05-25 04:24 UTC, dadaa commented on index.html
> +      for (let i = existUsersNumber; i < userAxisOrders.length; i++) {
もうこのループ要らなくなりそうな気がします。

2021-05-25 07:41 UTC, nboufSD commented on index.html
> +      const userAxisOrders = metadata?.userOrders || [];
nullになることはなかったので、削除しました。

2021-05-25 07:54 UTC, nboufSD commented on index.html
> +      for (let i = existUsersNumber; i < userAxisOrders.length; i++) {
ここでループを使わなくてもいけたので、削除しました！
（もうorderも使用する必要もなくなったので、orderも削除しました！）

2021-05-25 08:52 UTC, dadaa requested changes

2021-05-25 08:52 UTC, dadaa commented on index.html
> +      const existUsersNumber = userAxisOrders.length;
もう要らないようです。

2021-05-25 08:52 UTC, dadaa commented on index.html
> +        userAxisOrders.push({ id: item.peerId, label: item.audience.name});
もうこのループで widget を作ってしまうので、`label:` はもう要らないのでは？

2021-05-25 08:52 UTC, dadaa commented on index.html
> +          text: userAxisOrders[userAxisOrders.length - 1].label,
text: label: item.audience.name,

2021-05-25 08:52 UTC, dadaa commented on index.html
> +              id: userAxisOrders[userAxisOrders.length - 1].id,
id: item.peerId

2021-05-25 08:52 UTC, dadaa commented on index.html
> +        const idPosition = userAxisOrders.findIndex(
userPosition?

2021-05-25 08:59 UTC, dadaa commented on index.html
> +        userAxisOrders.push({ id: item.peerId, label: item.audience.name});
あー、そうだとすれば、もう id だけ push すればいいんじゃない？

2021-05-25 10:08 UTC, nboufSD commented on index.html
> +      const existUsersNumber = userAxisOrders.length;
コメントを削除するということであってますか？（削除しました）

2021-05-25 10:10 UTC, nboufSD commented on index.html
> +        userAxisOrders.push({ id: item.peerId, label: item.audience.name});
resultに含まれるnameをidで検索すれば、labelがなくても書けるのですが、どちらが良いのでしょうか？

2021-05-25 10:12 UTC, nboufSD commented on index.html
> +        userAxisOrders.push({ id: item.peerId, label: item.audience.name});
あ、すいません！
勘違いしてました…

2021-05-25 10:13 UTC, nboufSD commented on index.html
> +          text: userAxisOrders[userAxisOrders.length - 1].label,
修正しました！

2021-05-25 10:14 UTC, nboufSD commented on index.html
> +              id: userAxisOrders[userAxisOrders.length - 1].id,
修正しました！

2021-05-25 10:14 UTC, nboufSD commented on index.html
> +        const idPosition = userAxisOrders.findIndex(
修正しました！

2021-05-25 10:23 UTC, nboufSD commented
labelとorderを消したので、変数名も変更しました！

2021-05-25 10:29 UTC, dadaa requested changes

2021-05-25 10:30 UTC, nboufSD commented on index.html
> +      const existUsersNumber = existUserIds.length;
すいません！削除しました

2021-05-25 10:43 UTC, nboufSD commented on index.html
> +        existUserIds.push({ id: item.peerId });
文字列だけ入れる様にしました！

2021-05-25 10:49 UTC, dadaa requested changes

2021-05-25 10:49 UTC, dadaa commented on index.html
> +        const index = existUserIds.findIndex(user => user === item.peerId);
existsUserIds はもはや文字列だけしか入っていないので、indexOf を使うべきでは？
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

良くみたら、index は単純に存在があるかどうかだけに使っているので、includes を使うべきでは？
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2021-05-25 10:57 UTC, nboufSD commented on index.html
> +        const index = existUserIds.findIndex(user => user === item.peerId);
includesを使用する様にしました！ありがとうございます！

2021-05-25 11:01 UTC, dadaa requested changes

2021-05-25 11:01 UTC, dadaa commented on index.html
> +          y: NAME_YCOOD * (existUserIds.length - 1),
非常に細かいところですが、
`existUserIds.push(item.peerId);` は、widget を作ってからでも良さそうなので、`existUserIds.push(item.peerId);` を後回しにすれば、
`y: NAME_YCOOD * existUserIds.length`
と、-1 をする処理を省くことができるので、そうしませんか？

2021-05-25 11:05 UTC, nboufSD commented on index.html
> +          y: NAME_YCOOD * (existUserIds.length - 1),
確かにその方が読みやすいですね…！
修正しました。

2021-05-25 11:13 UTC, dadaa requested changes

2021-05-25 11:13 UTC, dadaa commented on index.html
>          miro.board.widgets.create({
create の仕様をみましたが、Promise を返すようです。
https://developers.miro.com/docs/interface-iboardwidgetscommands#section-create
なので、ここで await を使ってしっかり待たないと、`miro.board.widgets.create` が思いのほか時間がかかったときに、配列数を y 座標に割り当てるところが壊れます。

2021-05-25 11:20 UTC, nboufSD commented on index.html
>          miro.board.widgets.create({
確かにそうですね…
他のcreateしているところも、awaitで揃える様にしました！

2021-05-25 11:21 UTC, dadaa approved these changes

2021-05-25 11:21 UTC, merged