fixed #96
mobility0/comado-plugin pull request #113
Opened 2021-05-25 11:49 UTC by nboufSD

2021-05-25 13:06 UTC, dadaa requested changes

2021-05-25 13:06 UTC, dadaa commented on index.html
> +      for (const record of result) {
さっきのプルリクでは、
`for (const item of result) {`
と、record ではなく item を使っていました。
一貫性を保つため、どっちかにしてください。

2021-05-25 13:06 UTC, dadaa commented on index.html
> +          (element) => element === record.peerId
`id => id === record.peerId`

2021-05-25 13:06 UTC, dadaa commented on index.html
> +          x: INIT_IMAGE_XCOOD + Number(record.time - newMinTimestamp) * TIME_MAGNIFICATION ,
Number 要らないんじゃない？

2021-05-25 14:11 UTC, nboufSD commented on index.html
> +      for (const record of result) {
すいません！
itemにしました。

2021-05-25 14:11 UTC, nboufSD commented on index.html
> +          (element) => element === record.peerId
修正しました！

2021-05-25 14:16 UTC, nboufSD commented on index.html
> +          x: INIT_IMAGE_XCOOD + Number(record.time - newMinTimestamp) * TIME_MAGNIFICATION ,
削除しました！

2021-05-25 21:03 UTC, dadaa requested changes

2021-05-25 21:03 UTC, dadaa commented on index.html
>          );
あー、indexOf 使った方が良いかも。
`const userPosition = existUserIds.indexOf(item.peerId);`

2021-05-25 21:03 UTC, dadaa commented on index.html
> +        await new Promise(r => setTimeout(r, 100));
あと、この wait がなぜ必要なのか、コメントを書いておいてください。

2021-05-26 04:05 UTC, nboufSD commented on index.html
>          );
修正しました！

2021-05-26 07:28 UTC, dadaa commented on index.html
> +        await new Promise(r => setTimeout(r, 100));
issue にあげておいてください。

2021-05-26 07:29 UTC, merged